
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
#
# Initial commit
#
# Changes to be committed:
#	new file:   DB/config.php
#	new file:   Library/PHPMailer/src/Exception.php
#	new file:   Library/PHPMailer/src/OAuth.php
#	new file:   Library/PHPMailer/src/PHPMailer.php
#	new file:   Library/PHPMailer/src/POP3.php
#	new file:   Library/PHPMailer/src/SMTP.php
#	new file:   Library/xlsx_reader.php
#	new file:   admin/add_admin.php
#	new file:   admin/add_config.php
#	new file:   admin/add_emp.php
#	new file:   admin/add_std.php
#	new file:   admin/gen_report.php
#	new file:   admin/index.php
#	new file:   admin/load_tt.php
#	new file:   admin/st_datas/Computer 7th_2019.xlsx
#	new file:   admin/st_datas/IT 7th_2019.xlsx
#	new file:   admin/st_datas/Mechanical 7th_2019.xlsx
#	new file:   admin/st_datas/Student-CS.xlsx
#	new file:   admin/st_datas/Student-IT.xlsx
#	new file:   admin/tt_datas/TimeTable - CS.xlsx
#	new file:   admin/tt_datas/TimeTable - IT.xlsx
#	new file:   admin/tt_datas/TimeTable.xlsx
#	new file:   assests/css/lib3.min.css
#	new file:   assests/css/main.css
#	new file:   assests/fonts/glyphicons-halflings-regular.eot
#	new file:   assests/fonts/glyphicons-halflings-regular.svg
#	new file:   assests/fonts/glyphicons-halflings-regular.ttf
#	new file:   assests/fonts/glyphicons-halflings-regular.woff
#	new file:   assests/fonts/glyphicons-halflings-regular.woff2
#	new file:   assests/js/jlib.min.js
#	new file:   assests/js/lib3.min.js
#	new file:   authorize.php
#	new file:   ccn_api/index.php
#	new file:   config/get_department.php
#	new file:   config/get_section.php
#	new file:   config/get_subject.php
#	new file:   dump/view_std.php
#	new file:   index.php
#	new file:   install.sql
#	new file:   readme.txt
#	new file:   register.php
#	new file:   student/api_get_st_att.php
#	new file:   student/api_get_st_rl_nm.php
#	new file:   student/index.php
#	new file:   teacher/api_get_sheet.php
#	new file:   teacher/api_get_std.php
#	new file:   teacher/index.php
#	new file:   teacher/mark_att.php
#	new file:   teacher/read_att.php
#	new file:   verify.php
#

